// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    "screen_sign_up" : "Sign Up",
    "screen_terms" : "Terms and conditions",
    "screen_top_up" : "Top Up",
    "screen_send" : "Send",
    "screen_recharge" : "Recharge",
    "screen_profile" : "Profile",
    "screen_transaction" : "Transactions History",
    "screen_mail_confirmation" : "Confirmation",
    "screen_upload_docs" : "Pick Documents",
    "screen_activate_product" : "Activate SIM Card",
    "screen_bundle_list_order" : "Products",
    "screen_forgot_password_confirm" : "Forgot password confirm",
    "screen_profile_user_data" : "Your Personal Info",
    "screen_bonus" : "Bonus",
    "screen_support" : "Support",
    "screen_rates" : "Rates",
    "screen_merchant_rates" : "%s Rates",
    "screen_code_scanner" : "Scan your ICCID",
    "screen_more" : "More",
    "screen_service" : "Service",
    "screen_payment_request" : "Payment Requests",
    "screen_payment_request_create" : "New Request",
    "screen_payment_request_details" : "Request Details",
    "screen_promo_code" : "Promo code",
    "screen_get_sim_card" : "SIM Card",
    "screen_payment_title" : "Payment",
    "send_mail_chooser_title" : "Send email via:",
    "choose_currency" : "Choose currency",
    "screen_reset_password" : "Reset password",
    "screen_select_phone_number" : "Select number",
    "screen_transactions" : "Transactions",
    "screen_complete_your_order" : "Complete your order",
    "screen_bank_transfer" : "Bank transfer",
    "screen_card_transfer" : "Card payment",
    "support_send_email_text" : "For all support inquiries please email",
    "profile_app_version" : "%1$s, version %2$s (%3$s)",
    "alert_title_cant_request_card" : "Can't request card",
    "alert_title_activation" : "Activation",
    "alert_title_attention" : "Attention",
    "alert_title_confirmation" : "Confirmation",
    "alert_title_error" : "Error",
    "alert_title_success" : "Success",
    "alert_title_check_input" : "Check Input",
    "alert_title_event" : "Event",
    "alert_button_ok" : "OK",
    "alert_button_show" : "Show",
    "alert_button_cancel" : "Cancel",
    "alert_button_close" : "Close",
    "alert_button_request" : "Request",
    "alert_button_confirm" : "Confirm",
    "alert_no_internet_title" : "No internet connection",
    "alert_no_internet_text" : "You are offline! Please check your internet connection and try again",
    "alert_cant_perform_action" : "You cannot perform this operation",
    "alert_you_are_blocked_text" : "You are blocked. Please contact our support",
    "alert_you_are_blocked" : "You are blocked and cannot perform this operation",
    "alert_you_are_blocked_button_support" : "Support",
    "alert_not_enough_money_text" : "You don't have enough money to transfer",
    "alert_only_one_club_text" : "You can have only one Club bundle",
    "alert_you_dont_have_card" : "You don't have payment card yet",
    "alert_you_need_sim_card" : "You need Sim to perform this operation",
    "alert_you_need_visa_card" : "You need Visa to perform this operation",
    "symbols" : "%d symbols",
    "at_least_symbols" : "At least %d symbols",
    "no_cards_available" : "No cards available. Please login later.",
    "alert_payment_error" : "Payment error",
    "alert_database_error" : "Please uninstall application and install newer version from the App Store",
    "alert_bundle_purchase_not_avaliable" : "Sorry, SIM cards are out of stock",
    "alert_min_amount" : "Minimum amount is %s",
    "alert_max_amount" : "Maximum amount is %s",
    "alert_make_choice" : "Please, make a choice",
    "alert_you_cannot_order_more" : "You cannot order more than %d items at once",
    "alert_confirmation_code_expires" : "Your sign up session has expired. If you want to sign up for the app, please, start the registration from the very beginning.",
    "alert_field_cant_be_empty" : "Field can't be empty",
    "alert_settings_title" : "Settings",
    "action_next" : "Next",
    "navbar_bonuses" : "Bonus",
    "navbar_inum" : "My %s",
    "navbar_sim" : "Telecom",
    "navbar_card" : "Visa",
    "navbar_more" : "More",
    "navbar_home" : "Home",
    "navbar_support" : "Support",
    "login_email_hint" : "Email",
    "login_password_hint" : "Password",
    "login_action_forgot_pass" : "Forgot password?",
    "login_action_sign_in" : "Sign In",
    "login_action_sign_up" : "Sign Up",
    "login_fail" : "Sign In Failed",
    "wrong_email" : "Wrong email",
    "login_create_account" : "Create account",
    "forgot_password_code" : "Code",
    "forgot_password_new_password" : "New password",
    "forgot_password_button_send" : "Send",
    "forgot_password_button_back" : "Back",
    "forgot_password_fail" : "Password request failed",
    "forgot_password_send_code" : "Confirmation code was sent to your email",
    "sign_up_terms" : "Terms and conditions %s",
    "sign_up_terms_club" : "%s CLUB Terms & Conditions",
    "sign_up_pivacy_policy" : "Privacy policy",
    "sign_up_agree_with_terms" : "I Agree to all Terms & Conditions",
    "sign_up_terms_conditions" : "Terms & Conditions",
    "sign_up_agree" : "I agree to all",
    "sign_up_button_sign_up" : "Sign Up",
    "sign_up_password_error" : "Password must be minimum 6 characters length, including 1 uppercase letter, 1 lowercase letter and 1 numeric character",
    "sign_up_fail" : "Sign Up Failed",
    "quantity_of_items" : "Choose quantity of products",
    "bank_instruction_email_text" : "Please, email for instructions:",
    "bank_instruction_title_order_id" : "Order ID:",
    "bank_instruction_title_product" : "Product:",
    "bank_instruction_title_order_total" : "Order total:",
    "bank_instruction_button_go_to_login" : "GO TO LOGIN",
    "sign_up_have_account" : "I have an account",
    "sign_up_payment_method" : "Payment method:",
    "quantity_of_items_bank_instruction" : "Quantity:",
    "sign_up_purchase_bundle" : "Purchase",
    "sign_up_buy_card_waiting_error" : "Payment is in process. Try to login later or email to support",
    "sign_up_buy_card_declined" : "Your previous card request was declined. Please retry or choose other option",
    "confirm_info_text" : "Confirmation code has been sent to your email\nPlease, enter confirmation code below",
    "confirm_fail" : "Confirmation Failed",
    "profile_logout" : "Sign Out",
    "profile_support" : "Support",
    "profile_limits" : "Increase limits",
    "profile_edit_address" : "Edit address",
    "profile_group_general" : "GENERAL",
    "profile_group_security" : "SECURITY",
    "profile_pin_app_unlock" : "PIN app unlock",
    "profile_pin_payment_confirmation" : "PIN payment confirmation",
    "profile_pin_setup" : "Set PIN",
    "profile_use_touch_id" : "Enable TouchID",
    "profile_data_field_phone" : "Contact phone",
    "profile_data_field_country" : "Country",
    "profile_data_field_city" : "City",
    "profile_data_field_street" : "Street Name",
    "profile_data_field_building" : "Street #",
    "profile_data_field_appartmens" : "Apartment",
    "profile_data_field_first_name" : "First Name",
    "profile_data_field_last_name" : "Last Name",
    "profile_data_field_dob" : "Date of Birth",
    "profile_data_field_post_index" : "Postal Code",
    "profile_data_field_post_index_hint" : "00000",
    "profile_data_no_18" : "You are under %s",
    "profile_data_fail" : "Please input your data in every field",
    "profile_data_menu_done" : "Done",
    "profile_data_address_hint" : "Address below will be used to deliver your SIM card",
    "profile_countries_list" : "Countries",
    "bundles_list_hint" : "Choose appropriate bundle",
    "bundles_no_data_in_list" : "No bundles",
    "bundles_rates" : "Rates",
    "bundles_order_fail" : "Order card failed",
    "bundles_total" : "Total:",
    "activate_iccid" : "ICCID",
    "activate_sim_num" : "Number",
    "activate_button_activate" : "Activate",
    "activate_hint_xxxx" : "XXXX",
    "activate_card_number_placeholder" : " - XXXX - XXXX - ",
    "activate_hint_month" : "MM",
    "activate_hint_year" : "YY",
    "activate_success" : "You successfully activated card",
    "activate_fail" : "Activation failed",
    "update_docs_button_send" : "Send",
    "update_docs_alert_max_docs_count" : "You have reached the maximum number of documents",
    "update_docs_select_file" : "Select file",
    "update_docs_from_camera" : "Take Photo",
    "update_docs_from_gallery" : "Select Document",
    "update_docs_hint_2docs" : "You need to upload %d document",
    "update_docs_hint_1docs" : "You need to upload %d more document(s)",
    "update_docs_hint_great" : "Great!",
    "update_docs_success" : "Your documents successfully uploaded",
    "update_docs_failed" : "Upload documents failed",
    "update_docs_file_to_large" : "Files are too large",
    "update_docs_remove_button" : "Remove Document",
    "update_docs_retake_photo" : "Retake Photo",
    "update_docs_select_new_photo" : "Select New",
    "update_docs_upload_photo" : "Upload Photo",
    "visa_title" : "My %s Visa Card",
    "visa_recharge_title" : "Recharge",
    "visa_recharge_description" : "Send funds to your payment card",
    "visa_show_pin_title" : "Show PIN",
    "visa_show_pin_description" : "Always protect your PIN",
    "visa_lost_title" : "Report Lost or Stolen",
    "visa_lost_description" : "Your card will be blocked",
    "visa_history_title" : "History",
    "visa_history_description" : "Your card transaction history",
    "visa_rates" : "Rates and Limits",
    "visa_alert_block_confirm_text" : "Are you sure to proceed card blocking?",
    "visa_expires_text" : "EXPIRES\nEND",
    "visa_report_lost_send_success" : "Your report was received",
    "visa_report_lost_send_fail" : "Your report wasn't sent",
    "visa_request_pin_fail" : "PIN Request failed",
    "visa_request_pin_hint" : "Please enter your card's CVV",
    "visa_request_pin_success" : "Your PIN is %s",
    "visa_alert_request_cvv_title" : "Request PIN",
    "visa_alert_request_cvv_hint" : "CVV",
    "inum_title" : "My %s Account",
    "inum_topup" : "Top Up",
    "inum_topup_description" : "Add funds to your %s account",
    "inum_send" : "Send",
    "inum_send_description" : "Send funds to another %s subscriber",
    "inum_history" : "History",
    "inum_history_description" : "%s subscriber transaction history",
    "inum_payment_request" : "Payment Requests",
    "inum_payment_request_description" : "Payment requests between %s subscribers",
    "inum_account" : "Account",
    "inum_text_payment_service" : "Payment services",
    "inum_text_payment_currency" : "Currency:",
    "sim_title" : "My %s SIM Card",
    "sim_recharge" : "Recharge",
    "sim_recharge_description" : "Send funds to your sim service",
    "sim_history" : "History",
    "sim_history_description" : "Service usage history",
    "sim_rate" : "Rates",
    "sim_rate_internet" : "Internet",
    "sim_rate_instruction" : "Internet Setup",
    "sim_rate_topconnect" : "Calling",
    "sim_rate_lang_suffix" : "en",
    "cah_top_up_lbl" : "%s Subscriber balance\nvia card:",
    "cah_recharge_lbl_sim" : "to service balance:",
    "cah_recharge_lbl_payment_request" : "to service balance:",
    "cah_recharge_lbl_visa" : "to card:",
    "cah_send_lbl" : "to %s Subscriber\nvia card:",
    "cah_send_lbl_cut" : "to %s Subscriber",
    "cah_available_for_recharge_lbl" : "Available for recharge",
    "cah_available_for_send_lbl" : "Available for send",
    "send_destination_phone_hint" : "Recipient number #",
    "send_btn_send" : "Send",
    "send_success" : "Your request was accepted",
    "send_fail" : "Transfer failed",
    "send_phone_check_fail" : "Recipient's phone number doesn't exist",
    "recharge_amount_hint" : "Amount",
    "recharge_alert_select_card" : "Select card",
    "recharge_button_recharge" : "Recharge",
    "recharge_success" : "Your request was accepted",
    "recharge_fail" : "Send funds failed",
    "fees_may_apply" : "Fees may apply",
    "raise_limit_button_title" : "Limits",
    "raise_limit_menu_upload_docs" : "Upload docs",
    "raise_limit_alert_text" : "We don't have your contact data or you haven't any VISA yet.",
    "raise_limit_alert_ok" : "Update profile",
    "top_up_btn_pay_topup" : "Proceed Payment",
    "top_up_payment_success" : "Thank you for payment!",
    "top_up_order_success" : "You successfully ordered new card",
    "top_up_order_total_price" : "%1$s %2$.2f",
    "top_up_commission" : "Commission 2.5%",
    "top_up_select_payment_service" : "Choose payment method",
    "top_up_quantity_hint" : "Quantity",
    "top_up_limits_error" : "Min %1$s %2$.2f, Max %3$s %4$.2f",
    "top_up_confirm_address" : "Address confirmation",
    "top_up_confirm_address_description" : "Is this address correct: %1$s?\nOrdered card(s) will be delivered to this address.",
    "transaction_settlement_date_label" : "Settlement date:\n%1$s",
    "transaction_menu_filters" : "Filters",
    "transaction_filters_all" : "All",
    "transaction_filters_incoming" : "Incoming",
    "transaction_filters_outgoing" : "Outgoing",
    "transaction_filters_withdraw_to_visa" : "Recharge Visa",
    "transaction_filters_withdraw_to_sim" : "Recharge Sim",
    "transaction_filters_top_up" : "Top Up",
    "transaction_filters_commission" : "Commission",
    "transaction_filters_transfer" : "Transfer",
    "transaction_filters_call" : "Call",
    "transaction_filters_sms" : "SMS",
    "transaction_filters_internet" : "Internet",
    "transaction_filters_recharge" : "Recharge",
    "transaction_filters_other" : "Other",
    "transaction_description_call_inbound" : "Call from %1$s duration: %2$s",
    "transaction_description_call_outbound" : "Call to %1$s duration: %2$s",
    "transaction_description_sms_inbound" : "SMS from %s",
    "transaction_description_sms_outbound" : "SMS to %s",
    "transaction_description_internet" : "Internet",
    "transaction_description_recharge_sim" : "Recharge",
    "transaction_description_withdraw_to_visa" : "Recharge Visa card #%1$s from %2$s subscriber SIM #%3$s",
    "transaction_description_withdraw_to_sim" : "Recharge service #%s",
    "transaction_description_top_up_web" : "%s subscriber balance TopUp",
    "transaction_description_top_up_terminal" : "%s subscriber balance TopUp",
    "transaction_description_commission" : "Commission",
    "transaction_description_transfer_inbound" : "Received from %1$s subscriber #%2$s",
    "transaction_description_transfer_outbound" : "Sent to %1$s subscriber #%2$s",
    "transaction_description_transfer_outbound_merchant" : "Sent to %s",
    "transaction_description_recharge_visa" : "Recharge from %s subscriber SIM account",
    "transaction_today" : "TODAY",
    "transaction_yesterday" : "YESTERDAY",
    "transaction_status_completed" : "Completed",
    "transaction_status_failed" : "Failed",
    "transaction_status_rolledback" : "Rolled Back",
    "transaction_status_pending" : "Pending",
    "transaction_no_data" : "No transactions",
    "transaction_load_failed" : "Failed to download the history",
    "scanner_flash_on" : "Flash [ON]",
    "scanner_flash_off" : "Flash [OFF]]",
    "scanner_auto_focus_on" : "Auto Focus [ON]",
    "scanner_auto_focus_off" : "Auto Focus [OFF]",
    "more_service" : "Services",
    "more_profile" : "Profile",
    "service_order_bundle" : "Purchase bundle",
    "service_activate_bundle" : "Activate bundle",
    "payment_request_incoming" : "Incoming",
    "payment_request_outgoing" : "Outgoing",
    "payment_request_create_hint_description" : "Description",
    "payment_request_create_btn_create" : "Request",
    "payment_request_create_phone_check_fail" : "Recipient's phone number doesn't exist",
    "payment_request_pending" : "Pending",
    "payment_request_history" : "Completed",
    "payment_request_from" : "From: %s",
    "payment_request_to" : "To: %s",
    "payment_request_status_pending" : "Pending",
    "payment_request_status_approved" : "Completed",
    "payment_request_status_cancelled" : "Cancelled",
    "payment_request_status_rejected" : "Rejected",
    "payment_request_status_expired" : "Expired",
    "payment_request_details_from" : "From:",
    "payment_request_details_to" : "To:",
    "payment_request_details_amount" : "Amount:",
    "payment_request_details_description" : "Description:",
    "payment_request_details_created" : "Created:",
    "payment_request_details_completed" : "Completed:",
    "payment_request_details_expired" : "Expired:",
    "payment_request_details_expires" : "Expires:",
    "payment_request_details_rejected" : "Rejected:",
    "payment_request_details_btn_approve" : "Approve",
    "payment_request_details_btn_reject" : "Reject",
    "payment_request_details_btn_report" : "Report",
    "payment_request_accept_success" : "Payment request was accepted",
    "payment_request_accept_fail" : "Payment request acception failed",
    "payment_request_reject_success" : "Payment request was rejected",
    "payment_request_reject_fail" : "Payment request rejection failed",
    "payment_request_cancel_success" : "Payment request was cancelled",
    "payment_request_cancel_fail" : "Payment request cancellation failed",
    "payment_request_report_success" : "Your report was sent",
    "payment_request_report_fail" : "Your report wasn't sent",
    "payment_request_create_success" : "Your request was accepted",
    "payment_request_create_fail" : "Request failed",
    "payment_request_create_error_my_phone_num" : "You can't send request to your account",
    "payment_request_report_alert_title" : "Report",
    "payment_request_report_alert_description" : "Please, describe reason",
    "payment_request_report_alert_btn_report" : "Report",
    "payment_request_payment_success" : "Thank you for payment!",
    "pin_enter_pin" : "Enter Passcode",
    "pin_select_pin" : "Select a pin",
    "pin_repeat_new_pin" : "Re-enter your new pin",
    "pin_btn_remove" : "Delete",
    "touch_id_confirm_request" : "Confirm request approval",
    "touch_id_confirm_transfer" : "Confirm transfer",
    "touch_id_unlock_app" : "Unlock app",
    "separator_my_cards" : "My cards",
    "separator_friends" : "Friends",
    "separator_contacts" : "Contacts",
    "select_card_search_hint" : "Start typing number",
    "select_card_manual_entry" : "Manual entry",
    "enter_promo_code" : "Enter promo code",
    "send_promo_code" : "Send promo code",
    "buy_card_question" : "Purchase SIM card",
    "activate_card_button" : "Activate your existing SIM card",
    "promo_text" : "In order to start using the service you need to have %s SIM card or promo code",
    "incorrect_email" : "Confirmation code is not sent. Probably email is incorrect",
    "promo_code_doesnt_exists" : "Unknown promo code",
    "user_exists" : "User with such email exists",
    "client_error_message" : "Service is unavailable",
    "login_pass_wrong" : "User and/or password not found",
    "push_message_topup_success" : "TopUp success",
    "push_message_transfer_received" : "Transfer received",
    "push_message_activation_success" : "Activation success",
    "push_message_recharge_visa_success" : "Recharge Visa success",
    "push_message_sim_success" : "Recharge Sim success",
    "push_message_new_pr_received" : "New payment request is received",
    "send_logs_button" : "Send logs"
};